# An example search config for TIGER + CE loss on Amazon-Beauty dataset with grid search
# If you want to add hyperparameter search space, use the "search__" prefix before the parameter name.

# global settings
pretrained_ckpt: null  # optional path to a pretrained checkpoint to load
test_eval: false  # whether to run evaluation on the test set instead of validation set
save_predictions: false  # whether to save the predictions on the test set

# dataset settings
dataset:
    type: genrec

    interaction_data_path: /path/to/movielens-1m/proc/user2item.pkl  # TODO: path to interaction data file
    textual_data_path: /path/to/movielens-1m/proc/item2title.pkl  # TODO: path to textual data file
    sid_cache_path: /path/to/outputs_quantizer/movielens-1m/test_processed_semantic_ids.npy  # TODO: path to sid cache file

    max_seq_length: 50
    min_seq_length: 1
    truncation_strategy: tail  # tail or slide, tile is equivalent to seqrec's truncation, slide is sliding window truncation

# collator settings
collator:
    type: genrec

    # no default parameters for quantizer collator at the moment

# model settings
model:
    type: tiger

    config:
        # base model parameters
        hidden_size: 256
        is_encoder_decoder: true
        decoder_start_token_id: 0
        pad_token_id: 0
        tie_word_embeddings: true
        use_cache: true

        # subclass model parameters
        num_heads: 4
        num_encoder_layers: 4
        num_decoder_layers: 4
        linear_dropout: 0
        attention_dropout: 0
        relative_attention_num_buckets: 32
        relative_attention_max_distance: 128
        enable_rope: false

# trainer settings
trainer:
    type: ce

    config:
        # training arguments - Run control
        do_train: true
        do_eval: true
        do_predict: true

        # training arguments - Optimization & schedule
        num_train_epochs: 200
        per_device_train_batch_size: 512
        per_device_eval_batch_size: 128
        gradient_accumulation_steps: 1  # batch_size = per_device_train_batch_size * num_devices * gradient_accumulation_steps
        learning_rate: 1.0e-3
        weight_decay: 0.1
        lr_scheduler_type: linear
        warmup_ratio: 0.05

        # training arguments - Evaluation & checkpointing
        metric_for_best_model: ndcg@5  # should exist in the metrics

        # training arguments - Parallelism & precision
        dataloader_num_workers: 0
        gradient_checkpointing: false
        bf16: false
        tf32: true

        # base trainer parameters
        eval_interval: 5  # run metrics every epoch
        train_stop_epoch: -1  # by default, do not stop training early
        metrics:
        - ["hr", {}]
        - ["ndcg", {}]
        - ["popularity", {p: [0.1, 0.2]}]
        - ["unpopularity", {p: [0.2, 0.4]}]
        model_loss_weight: 0.0
        top_k: [1, 5, 10]
        num_beams: 10

        # subclass trainer parameters
        ce_temperature: 1.0
